brands_list = [
    "Discord", "Twitter", "Instagram", "YouTube", "News", "PayPal", "Patreon", "Ko-fi", "®", "At&T", 
    "Facebook", "Google", "Apple", "Microsoft", "Amazon", "Netflix", "Spotify", "Tesla", "LinkedIn", 
    "Snapchat", "Pinterest", "TikTok", "Reddit", "WhatsApp", "WeChat", "Alibaba", "IBM", "Intel", 
    "Samsung", "Sony", "Huawei", "Oracle", "Salesforce", "Zoom", "Slack", "Shopify", "Uber", "Lyft", 
    "Airbnb", "Dropbox", "Adobe", "Nvidia", "Dell", "HP", "Xiaomi", "Asus", "Lenovo", "Razer", 
    "Twitch", "Baidu", "JD.com", "Spotify", "SoundCloud", "Pandora", "Flickr", "Vimeo", "Medium", 
    "Tumblr", "Quora", "Yelp", "TripAdvisor", "Booking.com", "Expedia", "eBay", "Etsy", "Alibaba", 
    "Stripe", "Square", "Payoneer", "Venmo", "Zelle", "CashApp", "Coinbase", "Binance", "Kraken", 
    "BitPay", "Ripple", "Stellar", "Litecoin", "Ethereum", "Dogecoin", "Polkadot", "Chainlink", 
    "Uniswap", "Aave", "Yearn", "Compound", "SushiSwap", "PancakeSwap", "OpenSea", "Rarible", 
    "MetaMask", "TrustWallet", "Ledger", "Trezor", "Robinhood", "Fidelity", "Charles Schwab", 
    "E*TRADE", "Vanguard", "TD Ameritrade", "Interactive Brokers", "Betterment", "Wealthfront", 
    "Acorns", "Stash", "M1 Finance", "SoFi", "Chime", "Revolut", "Monzo", "N26", "Ally", "Aspiration", 
    "Varo", "Simple", "Current", "Starling", "TransferWise", "Western Union", "MoneyGram", 
    "Remitly", "Xoom", "WorldRemit", "OFX", "TransferGo", "Paysend", "Paysera", "Skrill", "Neteller", 
    "Qonto", "Kabbage", "BlueVine", "OnDeck", "Funding Circle", "LendingClub", "Upstart", "Avant", 
    "Prosper", "Credible", "Earnest", "LendKey", "Splash Financial", "CommonBond", "College Ave", 
    "Discover Student Loans", "Sallie Mae", "Navient", "Nelnet", "FedLoan Servicing", "Great Lakes", 
    "MyFedLoan", "MOHELA", "Aspire Servicing Center", "HESC", "CSMC", "EdFinancial", "CornerStone", 
    "Granite State", "OSLA Servicing", "MDRC", "NextGenVest", "Pay4Ward", "Simplify", "Tuition.io", 
    "Student Loan Hero", "Bank of America", "JPMorgan Chase", "Wells Fargo", "Citibank", "Goldman Sachs", 
    "Morgan Stanley", "HSBC", "Barclays", "UBS", "Credit Suisse", "Deutsche Bank", "BNP Paribas", 
    "Societe Generale", "Royal Bank of Canada", "Toronto-Dominion Bank", "Bank of Montreal", 
    "Scotiabank", "National Bank of Canada", "Royal Bank of Scotland", "Lloyds Bank", "Standard Chartered", 
    "Santander", "BBVA", "CaixaBank", "ING", "Rabobank", "Unicredit", "Intesa Sanpaolo", "Mizuho", 
    "Sumitomo Mitsui", "Nomura", "Mitsubishi UFJ", "Resona", "Shinsei", "Norinchukin", "Rakuten", 
    "SoftBank", "Ping An", "China Merchants Bank", "Industrial and Commercial Bank of China", 
    "China Construction Bank", "Agricultural Bank of China", "Bank of China", "China CITIC Bank", 
    "China Everbright Bank", "HDFC Bank", "ICICI Bank", "State Bank of India", "Axis Bank", 
    "Kotak Mahindra Bank", "Yes Bank", "Punjab National Bank", "Bank of Baroda", "Canara Bank", 
    "Union Bank of India", "Indian Bank", "Central Bank of India", "IDBI Bank", "IndusInd Bank", 
    "Federal Bank", "Bandhan Bank", "DBS Bank", "OCBC Bank", "UOB", "Standard Chartered Bank", 
    "Maybank", "CIMB", "Public Bank", "RHB Bank", "AmBank", "Hong Leong Bank", "Malayan Banking", 
    "Bangkok Bank", "Kasikornbank", "Krung Thai Bank", "Siam Commercial Bank", "PT Bank Mandiri", 
    "PT Bank Central Asia", "PT Bank Rakyat Indonesia", "PT Bank Negara Indonesia", "ANZ", 
    "Commonwealth Bank", "National Australia Bank", "Westpac", "Macquarie", "UBank", "Bankwest", 
    "AMP", "Suncorp", "Bendigo Bank", "Bank of Queensland", "ING Australia", "HSBC Australia", 
    "Rabobank Australia", "ME Bank", "People's Choice Credit Union", "Heritage Bank", "Newcastle Permanent", 
    "Beyond Bank", "Great Southern Bank", "Teachers Mutual Bank", "Australian Military Bank", 
    "Defence Bank", "Police Bank", "Firefighters Mutual Bank", "Australian Unity Bank", "Bank Australia", 
    "MyState Bank", "Qudos Bank", "Unity Bank", "Move Bank", "Regional Australia Bank", "Greater Bank", 
    "IMB Bank", "Endeavour Mutual Bank", "Southern Cross Credit Union", "Australian Unity Bank", 
    "Tic:Toc", "Nano Digital Home Loans", "Athena Home Loans", "86 400", "Volt Bank", "Xinja Bank",
    "Visa", "MasterCard", "American Express", "Discover", "JCB", "UnionPay", 
    "Paytm", "Alipay", "WePay", "Afterpay", "Klarna", "Sezzle", "Affirm", 
    "ShopRunner", "Rakuten", "Groupon", "LivingSocial", "RetailMeNot", 
    "Honey", "Ebates", "Grubhub", "DoorDash", "Uber Eats", "Postmates", 
    "Seamless", "Zomato", "Swiggy", "Deliveroo", "Just Eat", "Foodpanda", 
    "Blue Apron", "HelloFresh", "Sun Basket", "Home Chef", "Freshly", 
    "Purple Carrot", "Green Chef", "EveryPlate", "Daily Harvest", 
    "Magic Spoon", "Sakara Life", "Nutrisystem", "Weight Watchers", 
    "Jenny Craig", "SlimFast", "Atkins", "Noom", "MyFitnessPal", 
    "Fitbit", "Garmin", "Peloton", "SoulCycle", "Orangetheory", "ClassPass", 
    "Equinox", "Planet Fitness", "Gold's Gym", "Anytime Fitness", 
    "Snap Fitness", "LA Fitness", "Crunch Fitness", "Lifetime Fitness", 
    "24 Hour Fitness", "Blink Fitness", "YMCA", "Bally Total Fitness", 
    "Curves", "Barre3", "Pure Barre", "Flywheel", "Zumba", "Jazzercise", 
    "Les Mills", "Beachbody", "Daily Burn", "Fitness Blender", "Tone It Up", 
    "FitOn", "Nike Training Club", "Adidas Training", "Under Armour", 
    "Reebok", "Puma", "New Balance", "Asics", "Brooks", "Hoka One One", 
    "Saucony", "Mizuno", "On Running", "Lululemon", "Athleta", "Fabletics", 
    "Gymshark", "Alo Yoga", "Outdoor Voices", "Rhone", "Vuori", "Sweaty Betty", 
    "Carbon38", "Lorna Jane", "Koral", "Beyond Yoga", "Varley", 
    "Balance Athletica", "Set Active", "Lilybod", "Beach Riot", "Year of Ours", 
    "Tory Sport", "FP Movement", "Victoria Sport", "Girlfriend Collective", 
    "Paragon Fitwear", "Nike", "Adidas", "Puma", "Under Armour", 
    "The North Face", "Columbia", "Patagonia", "Arc'teryx", "Marmot", 
    "Mountain Hardwear", "Black Diamond", "Outdoor Research", "REI", 
    "Backcountry", "Moosejaw", "GearLab", "Cabela's", "Bass Pro Shops", 
    "Dick's Sporting Goods", "Academy Sports + Outdoors", "Sportsman's Warehouse", 
    "Big 5 Sporting Goods", "Gander Outdoors", "Camping World", "Field & Stream", 
    "L.L.Bean", "Orvis", "Eddie Bauer", "Filson", "Huckberry", "Go Outdoors", 
    "Decathlon", "Halfords", "Wiggle", "Ribble Cycles", "Evans Cycles", 
    "Chain Reaction Cycles", "Competitive Cyclist", "Canyon", "Trek", 
    "Specialized", "Cannondale", "Giant", "Scott", "Santa Cruz", "Yeti", 
    "Pivot", "BMC", "Cervelo", "Pinarello", "Colnago", "De Rosa", "Bianchi", 
    "Merida", "Orbea", "KTM", "Focus", "Cube", "Felt", "Lapierre", 
    "Rocky Mountain", "Norco", "GT Bicycles", "Mongoose", "Schwinn", 
    "Raleigh", "Diamondback", "Electra", "Brompton", "Tern", "Dahon", 
    "Birdy", "Strida", "Montague", "Xtracycle", "Yuba", "Rad Power Bikes", 
    "Aventon", "Juiced Bikes", "Ride1UP", "Super73", "Sondors", "Pedego", 
    "Blix", "Gazelle", "Riese & Müller", "Haibike", "Bulls", "Stromer", 
    "GoCycle", "VanMoof", "Cowboy", "Zycle", "Woom", "Islabikes", 
    "Frog Bikes", "Early Rider", "Strider", "Prevelo", "Guardian Bikes", 
    "Cleary Bikes", "Pello Bikes", "Spawn Cycles", "Commencal", "Whyte", 
    "Orange", "Nukeproof", "Saracen", "Vitus", "Marin", "Ibis", 
    "Evil Bikes", "Transition", "Devinci", "Norco", "Rocky Mountain", 
    "Pivot", "Santa Cruz", "Juliana", "Liv", "Canyon", "Yeti", 
    "Alchemy", "Ellsworth", "Foes", "Intense", "Knolly", "Mondraker", 
    "Polygon", "Revel", "Salsa", "VAAST", "Alchemy", "Banshee", 
    "Chromag", "Da Vinci", "Foes", "Guerrilla Gravity", "Liteville", 
    "Nicolai", "Pole", "Revel", "Starling", "Titanium", "VAAST", 
    "Why Cycles", "Moots", "Seven Cycles", "Eriksen", "Firefly", 
    "Kent Eriksen", "Litespeed", "Independent Fabrication", "Strong Frames", 
    "Rock Lobster", "Zinn Cycles", "Trek", "Specialized", "Giant", 
    "Cannondale", "Scott", "Merida", "BMC", "Cervelo", "Pinarello", 
    "Colnago", "De Rosa", "Bianchi", "Argon 18", "Look", "Orbea", 
    "Focus", "Canyon", "Cube", "Wilier", "Ritte", "Parlee", "Open", 
    "Allied Cycle Works", "Factor", "Felt", "Kona", "Salsa", 
    "Surly", "Niner", "Yeti", "Santa Cruz", "Ibis", "Pivot", 
    "Transition", "Rocky Mountain", "Devinci", "Norco", "Evil Bikes", 
    "Juliana", "Liv", "Alchemy", "Ellsworth", "Knolly", "Mondraker", 
    "Polygon", "Whyte", "Orange", "Saracen", "Vitus", "Marin", 
    "Yeti", "Cotic", "Curtlo", "Foes", "Guerrilla Gravity", 
    "Liteville", "Nicolai", "Starling", "Titanium", "VAAST", 
    "Why Cycles", "Moots", "Seven Cycles", "Eriksen", "Firefly", 
    "Kent Eriksen", "Litespeed", "Independent Fabrication", 
    "Strong Frames", "Rock Lobster", "Zinn Cycles", "S-Works",
    "Amazon", "Apple", "Google", "Microsoft", "Samsung", "Sony", 
    "LG", "Huawei", "Xiaomi", "OnePlus", "Lenovo", "Dell", 
    "HP", "Asus", "Acer", "Toshiba", "Panasonic", "Philips", 
    "Sharp", "Nokia", "Motorola", "HTC", "BlackBerry", "ZTE", 
    "Oppo", "Vivo", "Realme", "Honor", "Meizu", "Alcatel", 
    "Micromax", "Lava", "Karbonn", "Infinix", "Tecno", "Itel", 
    "Blu", "Sony Ericsson", "Siemens", "Palm", "Compaq", 
    "Gateway", "eMachines", "Packard Bell", "Alienware", 
    "Razer", "MSI", "Gigabyte", "Corsair", "NZXT", "Thermaltake", 
    "Cooler Master", "EVGA", "ASRock", "Biostar", "Zotac", 
    "Seagate", "Western Digital", "Kingston", "Crucial", "G.Skill", 
    "HyperX", "ADATA", "Patriot", "Toshiba Memory", "Samsung Memory", 
    "SanDisk", "Lexar", "PNY", "Transcend", "Verbatim", 
    "QNAP", "Synology", "Drobo", "Buffalo", "Netgear", 
    "Linksys", "TP-Link", "D-Link", "Ubiquiti", "Cisco", 
    "Aruba", "Juniper", "Fortinet", "Palo Alto Networks", 
    "Check Point", "SonicWall", "WatchGuard", "Trend Micro", 
    "McAfee", "Symantec", "Norton", "Kaspersky", "Bitdefender", 
    "ESET", "Avast", "AVG", "Sophos", "Malwarebytes", 
    "Webroot", "Carbon Black", "CrowdStrike", "Cylance", 
    "SentinelOne", "FireEye", "F-Secure", "G Data", 
    "Panda Security", "ZoneAlarm", "Comodo", "Microsoft Defender", 
    "Opera", "Mozilla", "Brave", "Vivaldi", "Maxthon", 
    "Yandex Browser", "UC Browser", "Epic Privacy Browser", 
    "Torch Browser", "SlimBrowser", "Avant Browser", 
    "SeaMonkey", "Waterfox", "Pale Moon", "Baidu Browser", 
    "QQ Browser", "360 Secure Browser", "Sogou Explorer", 
    "Samsung Internet", "Kiwi Browser", "DuckDuckGo Browser", 
    "Cliqz", "Coast by Opera", "Aloha Browser", "InBrowser", 
    "Cocoon Browser", "Ghostery Privacy Browser", 
    "Orbot", "Tor Browser", "CryptoTab", "Phoenix Browser", 
    "Mint Browser", "JioBrowser", "CM Browser", "Apus Browser", 
    "XBrowser", "Dolphin Browser", "Adblock Browser", 
    "ARMOR VPN", "Bear VPN", "CyberGhost", "ExpressVPN", 
    "NordVPN", "Private Internet Access", "ProtonVPN", 
    "Surfshark", "VyprVPN", "Windscribe", "Hotspot Shield", 
    "HideMyAss!", "IPVanish", "Mullvad", "TunnelBear", 
    "UltraVPN", "ZenMate", "Atlas VPN", "Avira Phantom VPN", 
    "Bitdefender VPN", "F-Secure FREEDOME", "HMA VPN", 
    "IVPN", "Kaspersky VPN", "McAfee Safe Connect", "Mozilla VPN", 
    "Norton Secure VPN", "Perimeter 81", "PrivateVPN", "PureVPN", 
    "StrongVPN", "Trust.Zone", "Unlocator VPN", "WeVPN", "ZeroVPN", 
    "ZoogVPN", "ZorroVPN", "AceVPN", "AirVPN", "Anonine VPN", 
    "AzireVPN", "BeeVPN", "BlackVPN", "BoxPN", "Buffered VPN", 
    "BTGuard", "BulletVPN", "CactusVPN", "Chameleon VPN", 
    "CryptoStorm", "Doublehop.me", "EarthVPN", "Encrypt.me", 
    "FastestVPN", "FrootVPN", "Getflix VPN", "Giganews", 
    "GoTrusted", "Hide.me", "ibVPN", "IronSocket", 
    "IVACY", "Le VPN", "LiquidVPN", "NordLayer", "OkayFreedom", 
    "OneVPN", "OVPN", "Perfect Privacy", "RA4W VPN", 
    "SaferVPN", "ShadeYou VPN", "SlickVPN", "SmartVPN", 
    "Speedify", "SpyOff", "StrongVPN", "SurfBouncer", 
    "SwissVPN", "TigerVPN", "VPN.ac", "VPN.ht", 
    "VPNBaron", "VPNHub", "VPNReactor", "VPNShazam", 
    "VPNUnlimited", "VPNSecure", "VPNTunnel", "Windscribe", 
    "Witopia", "WorldVPN", "ZenVPN", "ZoogVPN", 
    "ZPN", "Trust.Zone", "TunnelBear", "Turbo VPN", 
    "Turbohide VPN", "UnblockVPN", "uVPN", "VeePN", 
    "VPN4All", "VPNArea", "VPNBook", "VPNLand", 
    "VPNMaster", "VPNRanks", "VPNReactor", "VPNSecure", 
    "VPN Unlimited", "X-VPN", "YouTube", "Yahoo", 
    "Yandex", "Zapya", "Zoho", "Zotero", "Zscaler"
]